import React, { useState } from 'react';
import { User } from '../../types';
import { api } from '../../services/api';
import { 
  CheckCircle2, 
  Clock, 
  MapPin, 
  AlertCircle, 
  ArrowRight, 
  QrCode, 
  UserCheck, 
  Activity,
  Sparkles
} from 'lucide-react';

interface CheckInScreenProps {
  user: User;
  onCheckInSuccess: () => void;
}

export const CheckInScreen: React.FC<CheckInScreenProps> = ({
  user,
  onCheckInSuccess
}) => {
  const [method, setMethod] = useState<'appointment' | 'phone'>('appointment');
  const [appointmentId, setAppointmentId] = useState('');
  const [phone, setPhone] = useState('');
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [checkInResult, setCheckInResult] = useState<any | null>(null);

  const handleCheckIn = async (e: React.FormEvent) => {
    e.preventDefault();
    setLoading(true);
    setError(null);

    try {
      const payload = method === 'appointment' 
        ? { appointmentId: appointmentId.trim() } 
        : { patientId: user.patientId, phone: phone.trim() };

      const res = await api.checkIn(payload);
      setCheckInResult(res);
    } catch (err: any) {
      setError(err.message || 'Check-in verification failed.');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div style={{ maxWidth: '640px', margin: '0 auto' }}>
      {/* Header */}
      <div style={{ textAlign: 'center', marginBottom: '28px' }}>
        <div className="hero-pill" style={{ marginBottom: '10px' }}>
          <UserCheck size={15} />
          <span>Hospital Arrival Verification</span>
        </div>
        <h1 style={{ fontSize: '2.2rem', marginBottom: '6px' }}>Manual Hospital Check-In</h1>
        <p style={{ color: 'var(--text-secondary)', fontSize: '0.95rem' }}>
          Please verify your arrival when you are inside the hospital clinic to enter the active queue.
        </p>
      </div>

      {checkInResult ? (
        /* Check-In Success Result Card */
        <div className="card" style={{ padding: '36px', textAlign: 'center' }}>
          <div style={{
            width: '68px',
            height: '68px',
            borderRadius: 'var(--radius-full)',
            background: 'var(--success-bg)',
            color: 'var(--success)',
            border: '2px solid var(--success-border)',
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
            margin: '0 auto 16px auto'
          }}>
            <CheckCircle2 size={36} />
          </div>

          <h2 style={{ fontSize: '1.8rem', marginBottom: '6px' }}>
            ✓ Check-In Successful
          </h2>
          <p style={{ color: 'var(--text-secondary)', fontSize: '0.92rem', marginBottom: '24px' }}>
            {checkInResult.alreadyCheckedIn ? 'You are already registered in the queue.' : 'Your queue token has been generated by the AI queue optimizer.'}
          </p>

          {/* Token Card */}
          <div style={{
            background: 'linear-gradient(135deg, #0f172a 0%, #1e293b 100%)',
            color: '#ffffff',
            borderRadius: 'var(--radius-xl)',
            padding: '32px',
            boxShadow: 'var(--shadow-xl)',
            marginBottom: '28px'
          }}>
            <span style={{ fontSize: '0.8rem', color: '#94a3b8', textTransform: 'uppercase', letterSpacing: '0.08em', fontWeight: 700 }}>
              YOUR OFFICIAL QUEUE TOKEN
            </span>
            <div className="queue-token-display">
              {checkInResult.tokenNumber}
            </div>

            <div className="queue-stats-row">
              <div className="queue-stat-item">
                <span className="queue-stat-label">Queue Position</span>
                <span className="queue-stat-value">#{checkInResult.queuePosition}</span>
              </div>
              <div className="queue-stat-item">
                <span className="queue-stat-label">Estimated Wait</span>
                <span className="queue-stat-value" style={{ color: '#38bdf8' }}>~{checkInResult.estimatedWaitTime} mins</span>
              </div>
              <div className="queue-stat-item">
                <span className="queue-stat-label">Assigned Room</span>
                <span className="queue-stat-value">{checkInResult.roomNo}</span>
              </div>
            </div>
          </div>

          <p style={{ fontSize: '0.92rem', color: 'var(--text-secondary)', marginBottom: '24px' }}>
            Attending Doctor: <strong>{checkInResult.doctorName}</strong> ({checkInResult.departmentName}). Please proceed to the waiting area near <strong>{checkInResult.roomNo}</strong>.
          </p>

          <button 
            className="btn btn-primary btn-lg"
            style={{ width: '100%' }}
            onClick={onCheckInSuccess}
          >
            <Activity size={18} />
            <span>Open Live Queue Tracker</span>
            <ArrowRight size={18} />
          </button>
        </div>
      ) : (
        /* Check-In Input Form */
        <div className="card" style={{ padding: '36px' }}>
          {error && (
            <div style={{
              background: 'var(--danger-bg)',
              border: '1px solid var(--danger-border)',
              borderRadius: 'var(--radius-md)',
              padding: '12px 16px',
              color: 'var(--danger)',
              fontSize: '0.88rem',
              marginBottom: '20px',
              display: 'flex',
              alignItems: 'center',
              gap: '8px'
            }}>
              <AlertCircle size={18} />
              <span>{error}</span>
            </div>
          )}

          {/* Mode Switcher */}
          <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '8px', marginBottom: '24px', background: 'var(--bg-muted)', padding: '4px', borderRadius: 'var(--radius-md)' }}>
            <button
              type="button"
              onClick={() => { setMethod('appointment'); setError(null); }}
              style={{
                padding: '8px',
                borderRadius: 'var(--radius-sm)',
                fontWeight: 600,
                fontSize: '0.88rem',
                background: method === 'appointment' ? '#ffffff' : 'transparent',
                color: method === 'appointment' ? 'var(--text-primary)' : 'var(--text-muted)',
                boxShadow: method === 'appointment' ? 'var(--shadow-sm)' : 'none'
              }}
            >
              By Appointment ID
            </button>
            <button
              type="button"
              onClick={() => { setMethod('phone'); setError(null); }}
              style={{
                padding: '8px',
                borderRadius: 'var(--radius-sm)',
                fontWeight: 600,
                fontSize: '0.88rem',
                background: method === 'phone' ? '#ffffff' : 'transparent',
                color: method === 'phone' ? 'var(--text-primary)' : 'var(--text-muted)',
                boxShadow: method === 'phone' ? 'var(--shadow-sm)' : 'none'
              }}
            >
              By Phone &amp; Patient ID
            </button>
          </div>

          <form onSubmit={handleCheckIn}>
            {method === 'appointment' ? (
              <div className="form-group">
                <label className="form-label" style={{ fontSize: '0.95rem' }}>
                  Enter Appointment ID *
                </label>
                <input 
                  type="text" 
                  className="form-input" 
                  placeholder="e.g. APT-2026-00124"
                  value={appointmentId}
                  onChange={e => setAppointmentId(e.target.value)}
                  style={{ fontSize: '1.05rem', letterSpacing: '0.04em', textTransform: 'uppercase' }}
                  required
                />
                <span className="form-hint">
                  Found on your booking confirmation voucher or email/SMS receipt. (Try: APT-2026-00124)
                </span>
              </div>
            ) : (
              <>
                <div className="form-group">
                  <label className="form-label">Patient ID</label>
                  <input 
                    type="text" 
                    className="form-input" 
                    value={user.patientId || ''} 
                    disabled
                  />
                </div>

                <div className="form-group">
                  <label className="form-label">Registered Phone Number *</label>
                  <input 
                    type="tel" 
                    className="form-input" 
                    placeholder="e.g. 9876543210"
                    value={phone}
                    onChange={e => setPhone(e.target.value)}
                    required
                  />
                </div>
              </>
            )}

            <button 
              type="submit" 
              className="btn btn-primary btn-lg" 
              style={{ width: '100%', marginTop: '16px' }}
              disabled={loading}
            >
              <CheckCircle2 size={18} />
              <span>{loading ? 'Verifying Arrival...' : 'CHECK IN NOW'}</span>
            </button>
          </form>

          {/* Quick Helper for Demo Testing */}
          <div style={{ marginTop: '24px', paddingTop: '16px', borderTop: '1px solid var(--border-color)', fontSize: '0.82rem', color: 'var(--text-muted)' }}>
            <strong>Demo Tip:</strong> Alex Carter has pre-scheduled appointment <code>APT-2026-00124</code> ready for immediate check-in!
          </div>
        </div>
      )}
    </div>
  );
};
